GET http://localhost:5000/tempatwisata


###
POST http://localhost:5000/tempatwisata
Content-Type: application/json

# {
#     "nama_tempatwisatamanado": "Malalayang Beach Walk",
#     "alamat_tempatwisatamanado": "Malalayang",
#     "jarak_tempatwisatamanado": "5KM",
#     "jambuka_tempatwisata": "Jam 8 Pagi",
#     "jamtutup_tempatwisata": "Jam 12 Malam",
#     "tiket_masuktempatwisata": "Rp15000"
# }
# {
#     "nama_tempatwisatamanado": "TES1",
#     "alamat_tempatwisatamanado": "1",
#     "jarak_tempatwisatamanado": "1",
#     "jambuka_tempatwisata": "1",
#     "jamtutup_tempatwisata": "1",
#     "tiket_masuktempatwisata": "1"

    
# }
# {
#     "nama_tempatwisatamanado": "Kawasan Megamas",
#     "alamat_tempatwisatamanado": "jalan piere tendean",
#     "jarak_tempatwisatamanado": "0.4KM",
#     "jambuka_tempatwisata": "jam 8 pagi",
#     "jamtutup_tempatwisata": "jam 11 malam",
#     "tiket_masuktempatwisata": "Rp3000"
# }
# {
#         "nama_tempatwisatamanado": "Taman Kesatuan Bangsa",
#     "alamat_tempatwisatamanado": "Jalan Dotulong Lasut",
#     "jarak_tempatwisatamanado": "0.1KM",
#     "jambuka_tempatwisata": "jam 8 pagi",
#     "jamtutup_tempatwisata": "jam 12 malam",
#     "tiket_masuktempatwisata": "Gratis"
# }
# {
#      "nama_tempatwisatamanado": "Malalayang Beach Walk",
#     "alamat_tempatwisatamanado": "Jalan Raya Sulawesi",
#     "jarak_tempatwisatamanado": "7KM",
#     "jambuka_tempatwisata": "jam 8 pagi",
#     "jamtutup_tempatwisata": "jam 11 malam",
#     "tiket_masuktempatwisata": "Rp10000"
# }
# {
#      "nama_tempatwisatamanado": "Wisata Rumah Alam",
#     "alamat_tempatwisatamanado": "Jalan Ring Road",
#     "jarak_tempatwisatamanado": "11KM",
#     "jambuka_tempatwisata": "jam 8 pagi",
#     "jamtutup_tempatwisata": "jam 11 malam",
#     "tiket_masuktempatwisata": "Rp35000"
# }
# {
#      "nama_tempatwisatamanado": "Makatete Hills",
#     "alamat_tempatwisatamanado": "Jalan Warembungan",
#     "jarak_tempatwisatamanado": "14KM",
#     "jambuka_tempatwisata": "jam 9 pagi",
#     "jamtutup_tempatwisata": "jam 10 malam",
    
# }
###
DELETE http://localhost:5000/tempatwisata/1
=======
#     "tiket_masuktempatwisata": "Rp30000"
# }
# {
#     "nama_tempatwisatamanado": "Malalayang Beach Walk",
#     "alamat_tempatwisatamanado": "Malalayang",
#      "jarak_tempatwisatamanado": "5KM",
#      "jambuka_tempatwisata": "Jam 8 Pagi",
#      "jamtutup_tempatwisata": "Jam 12 Malam",
#      "tiket_masuktempatwisata": "Rp15000"
# }

# {
#     "nama_tempatwisatamanado": "Soekarno Bridge",
#     "alamat_tempatwisatamanado": "Jl. Boulevard II, Kota Manado, Sulawesi Utara",
#      "jarak_tempatwisatamanado": "3.8KM",
#      "jambuka_tempatwisata": "24 Jam",
#      "jamtutup_tempatwisata": "-",
#      "tiket_masuktempatwisata": "Gratis"
# }
# {
#     "nama_tempatwisatamanado": "Yesus Memberkati Statue",
#     "alamat_tempatwisatamanado": "CRQX+53R, Winangun Satu, Malalayang, Manado City, North Sulawesi",
#      "jarak_tempatwisatamanado": "8.7KM",
#      "jambuka_tempatwisata": "24 Jam",
#      "jamtutup_tempatwisata": "-",
#      "tiket_masuktempatwisata": "Gratis"
# }
# {
#     "nama_tempatwisatamanado": "Kathedral Hati Tersuci Maria",
#      "alamat_tempatwisatamanado": "Jalan Samratulangi wenang utara",
#       "jarak_tempatwisatamanado": "4.7KM",
#       "jambuka_tempatwisata": "24 Jam",
#       "jamtutup_tempatwisata": "-",
#       "tiket_masuktempatwisata": "-"
# }

{
    "nama_tempatwisatamanado": "Wakeke",
     "alamat_tempatwisatamanado": "Jalan Samratulangi wenang utara",
      "jarak_tempatwisatamanado": "4.7KM",
      "jambuka_tempatwisata": "jam 8 pagi",
      "jamtutup_tempatwisata": "jam 7 malam",
      "tiket_masuktempatwisata": "-"
}
###
DELETE http://localhost:5000/tempatwisata/10

###
DELETE http://localhost:5000/tempatwisata/2

###
PATCH http://localhost:5000/tempatwisata/7
Content-Type: application/json

{
    "id": 7,
     "nama_tempatwisatamanado": "Jl kuala popo",
    "alamat_tempatwisatamanado": "Jalan krida",
    "jarak_tempatwisatamanado": "10KM",
    "tiket_masuktempatwisata": "Rp10000"
    
}



###
GET http://localhost:5000/product/1


